# This workflow will test building a Python Package when a PR to main is created.

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build
        run: |
          pip list
          python -m build

      - name: Install from whl
        run: |
          pip list
          python -m pip install dist/*.whl

      - name: Import
        run: |
          cd ..
          python -c "import caf.base; caf.base.__version__;"
